config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resources :events, only: [:new, :create, :show]

    # Sessions
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

    root 'events#index'

    # Create invitations
    get '/events/:id/invitations/new', to: 'invitations#new', as: 'new_invitation'
    post '/events/:id/invitations/new', to: 'invitations#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :invitations
  has_many :invitees, through: :invitations, source: :invitee

  scope :past_events, -> { where('date < ?', DateTime.now) }
  scope :upcoming_events, -> { where('date > ?', DateTime.now) }

  def self.find_upcoming_events
    upcoming_events.order('created_at DESC').pluck(:title, :id)
  end

  def self.find_past_events
    past_events.order('created_at DESC').pluck(:title, :id)
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invitee, class_name: 'User'
  belongs_to :event, class_name: 'Event'

  def self.list_invitees(event)
    where(event_id: event.id)
      .pluck(:invitee_id)
  end

  def self.name_invitees(list)
    User.where({ id: list })
      .pluck(:name)
  end

  def self.list_past_invitations(user)
    Event.past_events.where({ id: where(invitee_id: user.id) })
      .pluck(:title, :id)
  end

  def self.list_upcoming_invitations(user)
    Event.upcoming_events.where({ id: where(invitee_id: user.id) })
      .pluck(:title, :id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, class_name: 'Event', foreign_key: 'creator_id'
  has_many :invitations
  has_many :attended_events, through: :invitations, source: :event

  def self.find_events_by_user(user)
    Event.where(creator_id: user.id)
      .pluck(:title, :id)
  end

  def self.find_invitations_by_user(user)
    Invitation.where(invitee_id: user.id).pluck(:event_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @past_events = Event.find_past_events
    @upcoming_events = Event.find_upcoming_events
  end

  def new
    @event = current_user.events.build
    @user = User.find(current_user.id)
  end

  def create
    @event = current_user.events.build(event_params)
    @user = User.find(current_user.id)

    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @creator = User.find(@event.creator_id)
    @event_invitees = Invitation.list_invitees(@event)
    @invitees = Invitation.name_invitees(@event_invitees)
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :description, :date, :time)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @current_event = Event.find(params[:id])
    @invitation = @current_event.invitations.build
  end

  def create
    @current_event = Event.find(params[:id])
    @email = invitation_params[:email]
    @user = User.where(email: @email).pluck(:id)
    @invitation = @current_event.invitations.build(invitee_id: @user[0])
    if @invitation.save
      redirect_to event_path(@current_event.id)
    else
      render :new
    end
  end

  private

  def invitation_params
    params.permit(:email, :authenticity_token, :commit, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to login_path
      flash.alert = 'User not found.'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_user_path
      session[:current_user] = @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @user_events = User.find_events_by_user(@user)
    @past_invitations = Invitation.list_past_invitations(@user)
    @upcoming_invitations = Invitation.list_upcoming_invitations(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_button_name(user)
    link_to user.name, user_path(user.id), class: 'btn btn-light mx-1' if user_signed_in?
  end

  def navbar_button_home
    link_to 'Home', root_path, class: 'btn btn-primary mx-1'
  end

  def navbar_button_new_event
    link_to 'New Event', new_event_path, class: 'btn btn-primary mx-1' if user_signed_in?
  end

  def navbar_button_log_out
    link_to 'Log out', logout_path, method: :delete, class: 'btn btn-primary mx-1' if user_signed_in?
  end

  def navbar_button_sign_up
    link_to 'Sign up', new_user_path, class: 'btn btn-primary mx-1' unless user_signed_in?
  end

  def navbar_button_log_in
    link_to 'Sign in', login_path, class: 'btn btn-primary mx-1' unless user_signed_in?
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def list_past_events(events)
    if events.empty?
      'There are no past events.'
    else
      content_tag :ul, class: 'd-flex flex-column' do
        events.collect { |event| concat link_to event[0], event_path(event[1]) }
      end
    end
  end

  def list_upcoming_events(events)
    if events.empty?
      'There are no upcoming events'
    else
      content_tag :ul, class: 'd-flex flex-column' do
        events.collect { |event| concat link_to event[0], event_path(event[1]) }
      end
    end
  end

  def show_invitees(invitees)
    if @invitees.empty?
      'There are no invitees yet'
    else
      content_tag :ul, class: 'd-flex flex-column' do
        invitees.collect { |invitee| concat(content_tag(:li, invitee)) }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def list_events(events)
    if events.empty?
      "You haven't created any events yet"
    else
      content_tag :ul, class: 'd-flex flex-column' do
        events.collect { |event| concat link_to event[0], event_path(event[1]) }
      end
    end
  end

  def list_invitations(invitations)
    if invitations.empty?
      "You don't have any events "
    else
      content_tag :ul, class: 'd-flex flex-column' do
        invitations.collect { |invitation| concat link_to invitation[0], event_path(invitation[1]) }
      end
    end
  end
end

app/views/events/index.html.erb
<div class="container-fluid d-flex">
  <div class="col">
    <h2>Past Events</h2>
    <%= list_past_events(@past_events) %>
  </div>
    <div class="col">
    <h2>Upcoming Events</h2>
    <%= list_upcoming_events(@upcoming_events) %>
  </div>
</div>

app/views/events/new.html.erb
<%= form_with model: @event do |form| %>
  <%= form.label(:title, "Title: ")%><br>
  <%= form.text_field :title, placeholder: "Title for your Event" %><br>
  
  <%= form.label(:description, "Description: ")%><br>
  <%= form.text_area :description, placeholder: "What is your event about?" %><br>
  
  <%= form.label(:location, "Location: ")%><br>
  <%= form.text_field :location, placeholder: "Bikini Bottom"%><br>  
  
  <%= form.label(:date, "Date: ")%><br>
  <%= form.date_field :date %><br>
  
  <%= form.label(:time, "Time: ")%><br>
  <%= form.time_field :time %><br><br>
  
  <%= form.submit("Submit")%>
<% end %>

app/views/events/show.html.erb
<div class= "container-fluid">
  <h1><%= @event.title%></h1>
  <p>Location: <%= @event.location %></p>
  <p>Date: <%= @event.date %></p>
  <p>Time: <%= @event.time %></p>
  </br>
  </br>

  <h3>Who is comming? </h3>
  <p><%= show_invitees(@invitees) %></p>
  <%= link_to 'Invite', new_invitation_path, class: 'btn btn-primary mx-1' if user_signed_in? %>

app/views/invitations/new.html.erb
<h1>Invite!</h1>

<%= form_tag new_invitation_path do %>

  Enter a user's email: <%= text_field_tag :email %>
  <%= submit_tag "Submit" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="mx-3">
    

    </div>
    <div><%= navbar_button_home %></div>
    <div class="container-fluid d-flex justify-content-end">
      <form class="d-flex">
        <%= navbar_button_name(current_user) %>
        <%= navbar_button_new_event %>
        <%= navbar_button_log_out %>
        <%= navbar_button_sign_up %>
        <%= navbar_button_log_in %>
      </form>
    </div>
  </nav>
  <% flash.each do |type, msg| %>
  <div class= "alert alert-info">
    <%= msg %>
  </div>
<% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with model: @user do |form| %>
    <%= form.label(:name, "name: ")%><br>
    <%= form.text_field :name, placeholder: "Eg. John Doe" %><br>  
    <%= form.label(:email, "Email: ")%><br>
    <%= form.email_field :email, placeholder: "john@doe.com"%><br>  
    <%= form.label(:password, "Password: ")%><br>
    <%= form.password_field :password, placeholder: "*****"%><br><br>  
    <%= form.submit("Submit")%>
  <% end %>

app/views/users/show.html.erb
<div class="container-fluid d-flex">
  <div class="col">
    <h2>Created events</h2>
    <%= list_events(@user_events) %>
  </div>
  <div class="col">
    <h2>Previously attended events</h2>
    <%= list_invitations(@past_invitations) %>
  </div>
    <div class="col">
    <h2>Upcoming events</h2>
    <%= list_invitations(@upcoming_invitations) %>
  </div>
</div>